service: twitter-icon-classifier-backend

provider:
  name: aws
  runtime: python3.6

plugins:
  - serverless-python-requirements

functions:
  hello:
    handler: handler.hello

custom:
  pythonRequirements:
    dockerizePip: false
    usePipenv: true