version: 2

jobs:
  deploy:
    docker:
      - image: circleci/node:10.13.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "backend/package-lock.json" }}
          - v1-dependencies-
      - run:
          name: Install Serverless Framework
          working_directory: backend
          command: sudo npm install -g
      - save_cache:
          paths:
            - backend/node_modules
          key: v1-dependencies-{{ checksum "backend/package-lock.json" }}
      - run:
          name: Deploy backend
          working_directory: backend
          command: sls deploy --stage prd -v
      - run:
          name: Deploy frontend
          command: aws s3 sync --delete ./frontend/ ${FRONTEND_S3_BUCKET}

workflows:
  version: 2
  deploy:
    jobs:
      - deploy
      # - deploy:
      #     filters:
      #       branches:
      #         only: master
           